# Generated by Django 4.1.7 on 2023-04-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_chats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_chat_link', models.CharField(max_length=100)),
                ('output_chat_link', models.CharField(max_length=100)),
                ('keywords', models.ManyToManyField(to='telegram_chats.keyword')),
                ('minus_keywords', models.ManyToManyField(to='telegram_chats.minusword')),
            ],
        ),
    ]
