# Generated by Django 4.2 on 2023-04-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_chats', '0002_groupchat'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(max_length=100)),
                ('api_hash', models.CharField(max_length=100)),
            ],
        ),
    ]
