# Generated by Django 4.2 on 2023-04-26 00:11

from django.db import migrations, models
import telegram_chats.storage


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_chats', '0004_remove_groupchat_minus_keywords_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessioncredentials',
            name='session_file',
            field=models.FileField(blank=True, null=True, storage=telegram_chats.storage.OverwriteStorage(), upload_to=''),
        ),
    ]
